version: '3'

services:
  web:
    build: ./react
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres:12-alpine
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'
    ports:
      - "55433:55433"
  api:
    build: ./api
    command: python manage.py runserver
    volumes:
      - ./api:/python
    ports:
      - "8000:8000"
    depends_on:
      - db
